---
#tasks for client
- name: copy clients-crt files to "{{ openvpn_dir }}/server"
  ansible.builtin.copy:
    src: "{{ openvpn_dir }}/easy-rsa/pki/issued/{{ item }}.crt"
    dest: "{{ openvpn_dir }}/server/{{ item }}.crt"
    mode: "0644"
    remote_src: true
  with_items:
    - "{{ openvpn_client }}"

- name: copy clients-key files to "{{ openvpn_dir }}/server"
  ansible.builtin.copy:
    src: "{{ openvpn_dir }}/easy-rsa/pki/private/{{ item }}.key"
    dest: "{{ openvpn_dir }}/server/{{ item }}.key"
    mode: "0644"
    remote_src: true
  with_items:
    - "{{ openvpn_client }}"

- name: "Ensure {{ openvpn_dir }}/users exists"
  file:
    path: "{{ openvpn_dir }}/users"
    state: directory
    mode: 0755

- name: copy files to "{{ openvpn_dir }}/users"
  ansible.builtin.copy:
    src: "{{ openvpn_dir }}/easy-rsa/pki/{{ item }}"
    dest: "{{ openvpn_dir }}/users/{{ item | basename }}"
    mode: "0644"
    remote_src: true
  loop:
    - ca.crt
    - ta.key

- name: copy clients-crt files to "{{ openvpn_dir }}/users"
  ansible.builtin.copy:
    src: "{{ openvpn_dir }}/easy-rsa/pki/issued/{{ item }}.crt"
    dest: "{{ openvpn_dir }}/users/{{ item }}.crt"
    mode: "0644"
    remote_src: true
  with_items:
    - "{{ openvpn_client }}"

- name: copy clients-key files to "{{ openvpn_dir }}/users"
  ansible.builtin.copy:
    src: "{{ openvpn_dir }}/easy-rsa/pki/private/{{ item }}.key"
    dest: "{{ openvpn_dir }}/users/{{ item }}.key"
    mode: "0644"
    remote_src: true
  with_items:
    - "{{ openvpn_client }}"

- name: "Register ca.crt"
  slurp: 
    src: "{{ openvpn_dir }}/ca.crt"
  register: openvpn_ca_cert

- name: "Register ta.key"
  slurp: 
    src: "{{ openvpn_dir }}/ta.key"
  register: openvpn_tls_auth  

- name: "Register client key"
  slurp: 
    src: "{{ openvpn_dir }}/users/{{ item }}.key"
  with_items:
    - "{{ openvpn_client }}"
  register: openvpn_client_key  

- name: "Register client crt"
  slurp: 
    src: "{{ openvpn_dir }}/users/{{ item }}.crt"
  with_items:
    - "{{ openvpn_client }}"
  register: openvpn_client_certs  

- name: Generate client config
  template:
    src: client.conf.j2
    dest: "{{ openvpn_dir }}/users/{{ item.0.item }}-{{ inventory_hostname }}.ovpn"
    owner: root
    group: root
    mode: 0400
  with_together:
    - "{{ openvpn_client_certs.results }}"
    - "{{ openvpn_client_key.results }}"

- name: Fetch client config
  ansible.builtin.fetch:
    src: "{{ openvpn_dir }}/users/{{ item }}-{{ inventory_hostname }}.ovpn"
    dest: "{{ playbook_dir }}/ovpn/{{ inventory_hostname }}-{{ item }}.ovpn"
  with_items:
    - "{{ openvpn_client }}"