---
# handlers file for ansible-role-openvpn
- name: restart openvpn
  service:
    name: openvpn
    state: restarted

- name: enable openvpn
  service:
    name: openvpn
    enabled: true
    state: started
    